[package]
name = "dol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Rust-native Data Operating Language facade"
readme = "../README.md"

[features]
default = ["derive"]
derive = ["dep:dol-macros"]
engine = ["dep:dol-engine"]
migrate = ["engine", "dep:dol-migrate"]
wire = ["dep:dol-wire"]
ml = ["engine", "dep:dol-ml"]

[dependencies]
dol-core = { path = "../crates/dol-core", version = "0.1.0" }
dol-macros = { path = "../crates/dol-macros", version = "0.1.0", optional = true }
dol-engine = { path = "../crates/dol-engine", version = "0.1.0", optional = true }
dol-migrate = { path = "../crates/dol-migrate", version = "0.1.0", optional = true }
dol-wire = { path = "../crates/dol-wire", version = "0.1.0", optional = true }
dol-ml = { path = "../crates/dol-ml", version = "0.1.0", optional = true }

[lints]
workspace = true

[dev-dependencies]
time = { version = "0.3", features = ["std"] }
