[package]
name = "dol-memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "memory engine adapter for DOL"

[dependencies]
dol-core = { path = "../../crates/dol-core", version = "0.1.0" }
dol-engine = { path = "../../crates/dol-engine", version = "0.1.0" }

[lints]
workspace = true

[dev-dependencies]
dol = { path = "../../dol" }
dol-conformance = { path = "../../crates/dol-conformance", version = "0.1.0" }
